apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-deployment
spec:
  replicas: 3  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
        - name: ecom-web
          image: praveenraj29/ecom-web:v3  # Replace with your Docker Hub image
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: db-config
          volumeMounts:
            - name: db-load-script
              mountPath: /var/www/html/db-load-script.sql
      volumes:
        - name: db-load-script
          configMap:
            name: db-load-script
---
apiVersion: v1
kind: Service
metadata:
  name: website-service
spec:
  selector:
    app: website
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer